site_name: Programació Didàctica. Mòdul XX. # Canviar pel nom del mpodul

theme: 
  name: material
  logo: img/logo.svg
  palette:
    primary: 'deep purple'

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - add_tables:
      ods_path: 'PD_DAM.ods' # Afegir aci el fitxer ods
      xslt_path: 'ods2html.xslt'

extra_css:
  - styles/taules.css

nav:  # La pàgina d'index no s'inclou aci perquè no aparega l'índex dos vegades al PDF
    - "1. Dades identificactives i contextualització": '1.Identificacio.md'
    - "2. Relació entre les unitats de competència i mòduls del cicle formatiu": '2.relacio_uc.md'
    - "3. Contribució dels RA a les competències professionals": '3.contribucio_ra.md'
    - "4. Resultats d'Aprenentatge, Criteris d'Avaluació i Continguts": '4.RAs_CAs_Continguts.md'
    - "5. Esquema general i seqüenciació de les UP": '5.esquema_general_up.md'
    - "6. Metodologia": '6.Metodologia.md'
    - "7. Recursos": '7.Recursos.md'
    - "8. Planificació de l'ús despais i equipaments": '8.Espais_equipament.md'
    - "9. Mesures d'atenció a la diversitat i inclusió": '9.Mesures_Atencio_Diversitat.md'
    - "10. Avaluació de l'aprenentatge": '10.Avaluacio.md'
    - "11. Activitats complementàries i extraescolars": '11.Activitats_Complementaries.md'
    - "12. Procediments per a l'avaluació de la programació i la pràctica docent": '12.Procediments_Avaluacio_PD.md'